const axios = require('axios');
  
  export const getToken = () => {
    return axios.get(`https://us.battle.net/oauth/token`, {
        auth: {
          username: process.env.CLIENT_ID,
          password: process.env.CLIENT_SECRET,
        },
        params: {
          grant_type: 'client_credentials',
        }
    }).then(response => response)
  }
 
  export const getCharacterProfile = (token, region, realm, characterName) => {
    let href = 'https://' + region + '.api.blizzard.com/wow/character/' +  realm + '/' + characterName + '?fields=appearance&access_token=' + process.env.access_token
    
    return axios.get(href, {
        headers: {
          Authorization: 'Bearer ' + process.env.access_token
        }
    }).then(response => response.data).catch(error => error)
  }

  export async function getRealmList(){
    let token = await getToken();
    let href = 'https://us.api.blizzard.com/wow/realm/status?access_token=' + process.env.access_token
    return axios.get(href, {
        headers: {
          Authorization: 'Bearer ' + process.env.access_token
        }
    }).then(response => {
      return getUsRealmNames(response.data.realms)
    })
  }
  
  const getUsRealmNames = realms => {
    let list = []
    Object.values(realms).forEach(value => {
            if (value["locale"] ===  "en_US"){
                list.push(value["name"]) 
            }
    })
    return list;
  }

export const classList = [
  "None",
  "Warrior",
  "Paladin",
  "Hunter",
  "Rogue",
  "Priest", 
  "DeathKnight",
  "Shaman",
  "Mage",
  "Warlock",
  "Monk",
  "Druid",
  "Demon Hunter"
]

export const realmList = [
    "Aerie Peak",
    "Anvilmar",
    "Arathor",
    "Antonidas",
    "Azuremyst",
    "Baelgun",
    "Blade's Edge",
    "Bladefist",
    "Bronzebeard",
    "Cenarius",
    "Darrowmere",
    "Draenor",
    "Dragonblight",
    "Echo Isles",
    "Galakrond",
    "Gnomeregan",
    "Hyjal",
    "Kilrogg",
    "Korialstrasz",
    "Lightbringer",
    "Misha",
    "Moonrunner",
    "Nordrassil",
    "Proudmoore",
    "Shadowsong",
    "Shu'Halo",
    "Silvermoon",
    "Skywall",
    "Suramar",
    "Uldum",
    "Uther",
    "Velen",
    "Windrunner",
    "Blackrock",
    "Blackwing Lair",
    "Bonechewer",
    "Boulderfist",
    "Coilfang",
    "Crushridge",
    "Daggerspine",
    "Dark Iron",
    "Destromath",
    "Dethecus",
    "Dragonmaw",
    "Dunemaul",
    "Frostwolf",
    "Gorgonnash",
    "Gurubashi",
    "Kalecgos",
    "Kil'Jaeden",
    "Lethon",
    "Maiev",
    "Nazjatar",
    "Ner'zhul",
    "Onyxia",
    "Rivendare",
    "Shattered Halls",
    "Spinebreaker",
    "Spirestone",
    "Stonemaul",
    "Stormscale",
    "Tichondrius",
    "Ursin",
    "Vashj",
    "Blackwater Raiders",
    "Cenarion Circle",
    "Feathermoon",
    "Sentinels",
    "Silver Hand",
    "The Scryers",
    "Wyrmrest Accord",
    "The Venture Co US",
    "Azjol-Nerub",
    "Doomhammer",
    "Icecrown",
    "Perenolde",
    "Terenas",
    "Zangarmarsh",
    "Kel'Thuzad",
    "Darkspear",
    "Deathwing",
    "Bloodscalp",
    "Nathrezim",
    "Shadow Council",
    "Aggramar",
    "Alexstrasza",
    "Alleria",
    "Blackhand",
    "Borean Tundra",
    "Cairne",
    "Dawnbringer",
    "Draka",
    "Eitrigg",
    "Fizzcrank",
    "Garona",
    "Ghostlands",
    "Greymane",
    "Grizzly Hills",
    "Hellscream",
    "Hydraxis",
    "Kael'thas",
    "Khaz Modan",
    "Kul Tiras",
    "Madoran",
    "Malfurion",
    "Malygos",
    "Mok'Nathal",
    "Muradin",
    "Nesingwary",
    "Quel'Dorei",
    "Ravencrest",
    "Rexxar",
    "Runetotem",
    "Sen'Jin",
    "Staghelm",
    "Terokkar",
    "Thunderhorn",
    "Vek'nilash",
    "Whisperwind",
    "Winterhoof",
    "Aegwynn",
    "Agamaggan",
    "Akama",
    "Archimonde",
    "Azgalor",
    "Azshara",
    "Balnazzar",
    "Blood Furnace",
    "Burning Legion",
    "Cho'gall",
    "Chromaggus",
    "Detheroc",
    "Drak'tharon",
    "Drak'thul",
    "Frostmane",
    "Garithos",
    "Gul'dan",
    "Hakkar",
    "Illidan",
    "Korgath",
    "Laughing Skull",
    "Mal'Ganis",
    "Malorne",
    "Mug'thol",
    "Stormreaver",
    "Sargeras",
    "The Underbog",
    "Thunderlord",
    "Wildhammer",
    "Farstriders",
    "Kirin Tor",
    "Moon Guard",
    "Scarlet Crusade",
    "Sisters of Elune",
    "Thorium Brotherhood",
    "Emerald Dream",
    "Lightninghoof",
    "Maelstrom",
    "Twisting Nether",
    "Area 52",
    "Arygos",
    "Bloodhoof",
    "Dalaran",
    "Drenden",
    "Durotan",
    "Duskwood",
    "Eldre'Thalas",
    "Elune",
    "Eonar",
    "Exodar",
    "Fenris",
    "Garrosh",
    "Gilneas",
    "Grizzly Hills",
    "Kargath",
    "Khadgar",
    "Llane",
    "Lothar",
    "Medivh",
    "Nazgrel",
    "Norgannon",
    "Shandris",
    "Stormrage",
    "Tanaris",
    "Thrall",
    "Trollbane",
    "Turalyon",
    "Uldaman",
    "Undermine",
    "Ysera",
    "Zul'jin",
    "Altar of Storms",
    "Alterac Mountains",
    "Andorhal",
    "Anetheron",
    "Anub'arak",
    "Arthas",
    "Auchindoun",
    "Black Dragonflight",
    "Bleeding Hollow",
    "Burning Blade",
    "Dalvengyr",
    "Demon Soul",
    "Eredar",
    "Executus",
    "Firetree",
    "Gorefiend",
    "Haomarush",
    "Jaedenar",
    "Lightning's Blade",
    "Mannoroth",
    "Magtheridon",
    "Scilla",
    "Shadowmoon",
    "Shattered Hand",
    "Skullcrusher",
    "Smolderthorn",
    "The Forgotten Coast",
    "Tortheldrin",
    "Warsong",
    "Ysondre",
    "Zuluhed",
    "Argent Dawn",
    "Earthen Ring",
    "Steamwheedle Cartel",
    "Ravenholdt",
]